project:
  type: website

website:
  title: "Ziwei Guo's Personal Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      page-footer:
        right: "&copy; 2024, Ziwei Guo"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute: 
  freeze: auto
